version: "3.7"

secrets:
  # Secrets are single-line text files where the sole content is the secret
  # Paths in this example assume that secrets are kept in local folder called ".secrets"
  DB_ROOT_PWD:
    file: .secrets/db_root_pwd.txt #edit with your path if differnt from my guide
  MYSQL_PWD:
    file: .secrets/mysql_pwd.txt #edit with your path if differnt from my guide


services:
  nginxpm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxpm
    restart: unless-stopped
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      DISABLE_IPV6: 'true'
      X_FRAME_OPTIONS: "sameorigin"
      # These are the settings to access your db
      DB_MYSQL_HOST: "npmdb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      # DB_MYSQL_PASSWORD: "npm"  # use secret instead
      DB_MYSQL_PASSWORD__FILE: /run/secrets/MYSQL_PWD
      DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./nginx-volume/data:/data #edit with your path
      - ./nginx-volume/letsencrypt:/etc/letsencrypt #edit with your path
    secrets:
      - MYSQL_PWD
    depends_on:
      - npmdb
    networks:
      - <Your_Network_Name> #edit with your network

  npmdb:
    image: jc21/mariadb-aria
    container_name: npmdb
    restart: unless-stopped
    environment:
      # MYSQL_ROOT_PASSWORD: "npm"  # use secret instead
      MYSQL_ROOT_PASSWORD__FILE: /run/secrets/DB_ROOT_PWD
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      # MYSQL_PASSWORD: "npm"  # use secret instead
      MYSQL_PASSWORD__FILE: /run/secrets/MYSQL_PWD
    volumes:
      - ./nginx-volume/mysql:/var/lib/mysql #edit with your path
    secrets:
      - DB_ROOT_PWD
      - MYSQL_PWD
    networks:
      - <Your_Network_Name> #edit with your network


networks:
  <Your_Network_Name>: #edit with your network
    external: true
